FORMAT: 1A
HOST: http://dashboard.seed-up.org/

# Seed-up API

## Users Collection [/users]

### List All Users [GET]

+ Response 200 (application/json)

        [
            {
                "name": "Liazidi",
                "fname": "Amine",
                "address": "23 Avenue Bernard Palissy, 92210 Saint Cloud",
                "email": "liazidiiamine@gmail.com",
                "status": "Membre de Seed-up"
            },
            {
                "name": "Boehm",
                "fname": "Steven",
                "address": "23 Avenue Bernard Palissy, 92210 Saint Cloud",
                "email": "boehm_s@etna-alternance.net",
                "status": "Membre de Seed-up"
            },
            {
                "name": "Boehm",
                "fname": "Erwan",
                "address": "23 Avenue Bernard Palissy, 92210 Saint Cloud",
                "email": "boehm_e@etna-alternance.net",
                "status": "Membre de Seed-up"
            }
        ]


### Create a New User [POST]

+ Request (application/json)

        {
            "name": "Liazidi",
            "fname": "Amine",
            "address": "23 Avenue Bernard Palissy, 92210 Saint Cloud",
            "email": "liazidiiamine@gmail.com",
            "status": 1,
            "password": "coucoutoi666"
        }

+ Response 201 (application/json)

    + Header

            Location: /users/1
            Etag: "686897696a7c876b7e"
    + Body

            {
                "id": 1
                "name": "Liazidi Amine",
                "email": "liazidiiamine@gmail.com",
                "created_at": "2015-08-05T08:40:51.620Z"
            }

## User [/users/{id}]

+ Parameters
    + id - A path variable that is required for a valid URL

### Retrieve a User [GET]

+ Request (application/json)

    + Header

            If-None-Match: "686897696a7c876b7e"
    + Body

            {
                "id": 0
            }

+ Response 200 (application/json)

        {
            "name": "Liazidi",
            "fname": "Amine",
            "address": "23 Avenue Bernard Palissy, 92210 Saint Cloud",
            "email": "liazidiiamine@gmail.com",
            "status": 1
        }

+ Response 304 (text/plain)

        "Not modified"

### Update a User [PUT]

+ Request (application/json)

        {
            "name": "Liazidi",
            "fname": "Amine",
            "address": "23 Avenue Bernard Palissy, 92210 Saint Cloud",
            "email": "liazidiiamine@gmail.com",
            "status": 1,
            "password": "coucoutoi666"
        }

+ Response 200 (application/json)

    + Header

            Location: /users/1
            Etag: "86549769456b7c876b"
    + Body

            {
                "name": "Liazidi Amine",
                "email": "liazidiiamine@gmail.com",
                "updated_at": "2015-08-05T08:40:51.620Z"
            }
